//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNWeb.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STNWeb.Assets.Resources.FileStrings", typeof(FileStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Agency: .
        /// </summary>
        public static string Agency_Label {
            get {
                return ResourceManager.GetString("Agency_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Collected/Processed: .
        /// </summary>
        public static string DateCollected_Label {
            get {
                return ResourceManager.GetString("DateCollected_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Taken:.
        /// </summary>
        public static string DateTaken_Label {
            get {
                return ResourceManager.GetString("DateTaken_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Uploaded:.
        /// </summary>
        public static string DateUploaded_Label {
            get {
                return ResourceManager.GetString("DateUploaded_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: .
        /// </summary>
        public static string File_Label {
            get {
                return ResourceManager.GetString("File_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Date:.
        /// </summary>
        public static string FileDate_Label {
            get {
                return ResourceManager.GetString("FileDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string FileDesc_Label {
            get {
                return ResourceManager.GetString("FileDesc_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation:.
        /// </summary>
        public static string FileElevation_Label {
            get {
                return ResourceManager.GetString("FileElevation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End: .
        /// </summary>
        public static string FileEnd_Label {
            get {
                return ResourceManager.GetString("FileEnd_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Data End Time: .
        /// </summary>
        public static string FileGoodEnd_Label {
            get {
                return ResourceManager.GetString("FileGoodEnd_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Data Start Time: .
        /// </summary>
        public static string FileGoodStart_Label {
            get {
                return ResourceManager.GetString("FileGoodStart_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HWM: .
        /// </summary>
        public static string FileHWM_Label {
            get {
                return ResourceManager.GetString("FileHWM_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Direction: .
        /// </summary>
        public static string FilePhotoDir_Label {
            get {
                return ResourceManager.GetString("FilePhotoDir_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Processed By: .
        /// </summary>
        public static string FileProcessor_Label {
            get {
                return ResourceManager.GetString("FileProcessor_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site: .
        /// </summary>
        public static string FileSite_Label {
            get {
                return ResourceManager.GetString("FileSite_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start: .
        /// </summary>
        public static string FileStart_Label {
            get {
                return ResourceManager.GetString("FileStart_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type: .
        /// </summary>
        public static string FileType_Label {
            get {
                return ResourceManager.GetString("FileType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File URL:.
        /// </summary>
        public static string FileURL_Label {
            get {
                return ResourceManager.GetString("FileURL_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTRUMENT DATA FILES.
        /// </summary>
        public static string InstrumentDF_Label {
            get {
                return ResourceManager.GetString("InstrumentDF_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Photographer: .
        /// </summary>
        public static string Photographer_Label {
            get {
                return ResourceManager.GetString("Photographer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Latitude (if different): .
        /// </summary>
        public static string PhotoLat_Label {
            get {
                return ResourceManager.GetString("PhotoLat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Longitude (if different): .
        /// </summary>
        public static string PhotoLong_Label {
            get {
                return ResourceManager.GetString("PhotoLong_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Name: .
        /// </summary>
        public static string Source_Label {
            get {
                return ResourceManager.GetString("Source_Label", resourceCulture);
            }
        }
    }
}
