//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNWeb.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class globalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal globalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STNWeb.Assets.Resources.globalStrings", typeof(globalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string Approval_Label {
            get {
                return ResourceManager.GetString("Approval_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisional.
        /// </summary>
        public static string ApprovalProvisional_Label {
            get {
                return ResourceManager.GetString("ApprovalProvisional_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Team:.
        /// </summary>
        public static string CollectTeam_Label {
            get {
                return ResourceManager.GetString("CollectTeam_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Team:.
        /// </summary>
        public static string DeployTeam_Label {
            get {
                return ResourceManager.GetString("DeployTeam_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string File_Label {
            get {
                return ResourceManager.GetString("File_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site HWMs.
        /// </summary>
        public static string HWM_Label {
            get {
                return ResourceManager.GetString("HWM_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Summary.
        /// </summary>
        public static string PeakSummary_Label {
            get {
                return ResourceManager.GetString("PeakSummary_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed By:.
        /// </summary>
        public static string ProposeMember_Label {
            get {
                return ResourceManager.GetString("ProposeMember_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated?.
        /// </summary>
        public static string PS_Estimated_Label {
            get {
                return ResourceManager.GetString("PS_Estimated_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member User Name: .
        /// </summary>
        public static string PS_MemberID_Label {
            get {
                return ResourceManager.GetString("PS_MemberID_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No peak summary info available.
        /// </summary>
        public static string PS_NoPeakSumm_Label {
            get {
                return ResourceManager.GetString("PS_NoPeakSumm_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Date: .
        /// </summary>
        public static string PS_PeakDate_Label {
            get {
                return ResourceManager.GetString("PS_PeakDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Date Estimated: .
        /// </summary>
        public static string PS_PeakDateEst_Label {
            get {
                return ResourceManager.GetString("PS_PeakDateEst_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Discharge: .
        /// </summary>
        public static string PS_PeakDischarge_Label {
            get {
                return ResourceManager.GetString("PS_PeakDischarge_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Discharge Estimated:.
        /// </summary>
        public static string PS_PeakDischargeEst_Label {
            get {
                return ResourceManager.GetString("PS_PeakDischargeEst_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Above Ground (ft):.
        /// </summary>
        public static string PS_PeakHAG_Label {
            get {
                return ResourceManager.GetString("PS_PeakHAG_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Above Ground Estimated:.
        /// </summary>
        public static string PS_PeakHAGEst_Label {
            get {
                return ResourceManager.GetString("PS_PeakHAGEst_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Stage (Elevation ft): .
        /// </summary>
        public static string PS_PeakStage_Label {
            get {
                return ResourceManager.GetString("PS_PeakStage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Stage Estimated: .
        /// </summary>
        public static string PS_PeakStageEst_Label {
            get {
                return ResourceManager.GetString("PS_PeakStageEst_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Time: .
        /// </summary>
        public static string PS_PeakTime_Label {
            get {
                return ResourceManager.GetString("PS_PeakTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Time Estimated: .
        /// </summary>
        public static string PS_PeakTimeEst_Label {
            get {
                return ResourceManager.GetString("PS_PeakTimeEst_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval Team:.
        /// </summary>
        public static string RetrieveTeam_Label {
            get {
                return ResourceManager.GetString("RetrieveTeam_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string Sensor_Label {
            get {
                return ResourceManager.GetString("Sensor_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Number: .
        /// </summary>
        public static string SiteNo_Label {
            get {
                return ResourceManager.GetString("SiteNo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Datum:.
        /// </summary>
        public static string VDatum_Label {
            get {
                return ResourceManager.GetString("VDatum_Label", resourceCulture);
            }
        }
    }
}
