//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNWeb.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HWMStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HWMStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STNWeb.Assets.Resources.HWMStrings", typeof(HWMStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank:.
        /// </summary>
        public static string Bank_Label {
            get {
                return ResourceManager.GetString("Bank_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (MM/DD/YYYY).
        /// </summary>
        public static string DateFormat_Label {
            get {
                return ResourceManager.GetString("DateFormat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation (ft): .
        /// </summary>
        public static string Elevation_Label {
            get {
                return ResourceManager.GetString("Elevation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event: .
        /// </summary>
        public static string Event_Label {
            get {
                return ResourceManager.GetString("Event_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagged Date:.
        /// </summary>
        public static string FlagDate_Label {
            get {
                return ResourceManager.GetString("FlagDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Collection Method: .
        /// </summary>
        public static string HCollectMethod_Label {
            get {
                return ResourceManager.GetString("HCollectMethod_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height above ground (ft): .
        /// </summary>
        public static string Height_Label {
            get {
                return ResourceManager.GetString("Height_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HWM Environment:.
        /// </summary>
        public static string HWMEnvironment_Label {
            get {
                return ResourceManager.GetString("HWMEnvironment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HWM Quality: .
        /// </summary>
        public static string HWMQual_Label {
            get {
                return ResourceManager.GetString("HWMQual_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HWM Type: .
        /// </summary>
        public static string HWMType_Label {
            get {
                return ResourceManager.GetString("HWMType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Description: .
        /// </summary>
        public static string LocationDesc_Label {
            get {
                return ResourceManager.GetString("LocationDesc_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker: .
        /// </summary>
        public static string Marker_Label {
            get {
                return ResourceManager.GetString("Marker_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HWM Notes: .
        /// </summary>
        public static string Notes_Label {
            get {
                return ResourceManager.GetString("Notes_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name: .
        /// </summary>
        public static string SiteName_Label {
            get {
                return ResourceManager.GetString("SiteName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Number: .
        /// </summary>
        public static string SiteNo_Label {
            get {
                return ResourceManager.GetString("SiteNo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stillwater Location?.
        /// </summary>
        public static string Stillwater_Label {
            get {
                return ResourceManager.GetString("Stillwater_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveyed Date:.
        /// </summary>
        public static string SurveyDate_Label {
            get {
                return ResourceManager.GetString("SurveyDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Collection Method: .
        /// </summary>
        public static string VCollectMethod_Label {
            get {
                return ResourceManager.GetString("VCollectMethod_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterbody:.
        /// </summary>
        public static string WaterBody_Label {
            get {
                return ResourceManager.GetString("WaterBody_Label", resourceCulture);
            }
        }
    }
}
