//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNWeb.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InstrumentsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstrumentsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STNWeb.Assets.Resources.InstrumentsStrings", typeof(InstrumentsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Conditions:.
        /// </summary>
        public static string Conditions_Label {
            get {
                return ResourceManager.GetString("Conditions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Location: .
        /// </summary>
        public static string DeploymentLocation_Label {
            get {
                return ResourceManager.GetString("DeploymentLocation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Type:.
        /// </summary>
        public static string DeploymentType_Label {
            get {
                return ResourceManager.GetString("DeploymentType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event: .
        /// </summary>
        public static string Event_Label {
            get {
                return ResourceManager.GetString("Event_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing Serial Number: .
        /// </summary>
        public static string HousingSerialNo_Label {
            get {
                return ResourceManager.GetString("HousingSerialNo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing Types:.
        /// </summary>
        public static string HousingType_Label {
            get {
                return ResourceManager.GetString("HousingType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval: .
        /// </summary>
        public static string Interval_Label {
            get {
                return ResourceManager.GetString("Interval_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Description: .
        /// </summary>
        public static string LocationDesc_Label {
            get {
                return ResourceManager.GetString("LocationDesc_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Date:.
        /// </summary>
        public static string LostDate_Label {
            get {
                return ResourceManager.GetString("LostDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: .
        /// </summary>
        public static string Notes_Label {
            get {
                return ResourceManager.GetString("Notes_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Date: .
        /// </summary>
        public static string RecoveryDate_Label {
            get {
                return ResourceManager.GetString("RecoveryDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string RetrievalNote_Label {
            get {
                return ResourceManager.GetString("RetrievalNote_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Brand:.
        /// </summary>
        public static string SensorBrand_Label {
            get {
                return ResourceManager.GetString("SensorBrand_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Type: .
        /// </summary>
        public static string SensorType_Label {
            get {
                return ResourceManager.GetString("SensorType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number: .
        /// </summary>
        public static string SerialNo_Label {
            get {
                return ResourceManager.GetString("SerialNo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string Status_Label {
            get {
                return ResourceManager.GetString("Status_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy Time:.
        /// </summary>
        public static string TimeStamp_Label {
            get {
                return ResourceManager.GetString("TimeStamp_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vented:.
        /// </summary>
        public static string Vented_Label {
            get {
                return ResourceManager.GetString("Vented_Label", resourceCulture);
            }
        }
    }
}
