//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNWeb.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LookupsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LookupsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STNWeb.Assets.Resources.LookupsStrings", typeof(LookupsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string AgencyAdd_createNew {
            get {
                return ResourceManager.GetString("AgencyAdd_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string AgencyCity_createNew {
            get {
                return ResourceManager.GetString("AgencyCity_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Name:.
        /// </summary>
        public static string AgencyName_createNew {
            get {
                return ResourceManager.GetString("AgencyName_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string AgencyPhone_createNew {
            get {
                return ResourceManager.GetString("AgencyPhone_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        public static string AgencyState_createNew {
            get {
                return ResourceManager.GetString("AgencyState_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip:.
        /// </summary>
        public static string AgencyZip_createNew {
            get {
                return ResourceManager.GetString("AgencyZip_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact Type:.
        /// </summary>
        public static string ContactType_createNew {
            get {
                return ResourceManager.GetString("ContactType_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deployment Priority:.
        /// </summary>
        public static string DeploymentP_createNew {
            get {
                return ResourceManager.GetString("DeploymentP_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deployment Priority:.
        /// </summary>
        public static string DeploymentPriority_createNew {
            get {
                return ResourceManager.GetString("DeploymentPriority_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deployment Type: .
        /// </summary>
        public static string DeplType_createNew {
            get {
                return ResourceManager.GetString("DeplType_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event Status: .
        /// </summary>
        public static string EventStat_createNew {
            get {
                return ResourceManager.GetString("EventStat_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event Type: .
        /// </summary>
        public static string EventType_createNew {
            get {
                return ResourceManager.GetString("EventType_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File Type: .
        /// </summary>
        public static string FileType_createNew {
            get {
                return ResourceManager.GetString("FileType_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Horizontal Collection Method: .
        /// </summary>
        public static string HCollectMethod_createNew {
            get {
                return ResourceManager.GetString("HCollectMethod_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Horizontal Datum:.
        /// </summary>
        public static string HDatum_createNew {
            get {
                return ResourceManager.GetString("HDatum_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Datum Abbreviation:.
        /// </summary>
        public static string HDatumAbbr_createNew {
            get {
                return ResourceManager.GetString("HDatumAbbr_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Datum Name:.
        /// </summary>
        public static string HDatumName_createNew {
            get {
                return ResourceManager.GetString("HDatumName_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New HWM Quality: .
        /// </summary>
        public static string HWMQual_createNew {
            get {
                return ResourceManager.GetString("HWMQual_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New HWM Type: .
        /// </summary>
        public static string HWMType_createNew {
            get {
                return ResourceManager.GetString("HWMType_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGENCIES.
        /// </summary>
        public static string Index_Agency_lb {
            get {
                return ResourceManager.GetString("Index_Agency_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT TYPES.
        /// </summary>
        public static string Index_ContactType_lb {
            get {
                return ResourceManager.GetString("Index_ContactType_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPLOYMENT PRIORITY.
        /// </summary>
        public static string Index_DeploymentP_lb {
            get {
                return ResourceManager.GetString("Index_DeploymentP_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENT STATUS.
        /// </summary>
        public static string Index_EventStat_lb {
            get {
                return ResourceManager.GetString("Index_EventStat_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENT TYPES.
        /// </summary>
        public static string Index_EventType_lb {
            get {
                return ResourceManager.GetString("Index_EventType_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE TYPES.
        /// </summary>
        public static string Index_FileType_lb {
            get {
                return ResourceManager.GetString("Index_FileType_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORIZONTAL COLLECTION METHODS.
        /// </summary>
        public static string Index_HCollectMethod_lb {
            get {
                return ResourceManager.GetString("Index_HCollectMethod_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORIZONTAL DATUMS.
        /// </summary>
        public static string Index_Hdatum_lb {
            get {
                return ResourceManager.GetString("Index_Hdatum_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HWM QUALITIES.
        /// </summary>
        public static string Index_HWMqual_lb {
            get {
                return ResourceManager.GetString("Index_HWMqual_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HWM TYPES.
        /// </summary>
        public static string Index_HWMtype_lb {
            get {
                return ResourceManager.GetString("Index_HWMtype_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTRUMENT COLLECTION CONDITIONS.
        /// </summary>
        public static string Index_InstrCollectCond_lb {
            get {
                return ResourceManager.GetString("Index_InstrCollectCond_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKERS.
        /// </summary>
        public static string Index_Marker_lb {
            get {
                return ResourceManager.GetString("Index_Marker_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETWORK NAMES.
        /// </summary>
        public static string Index_NetworkName_lb {
            get {
                return ResourceManager.GetString("Index_NetworkName_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SITE LOCATION TYPE IN NETWORK.
        /// </summary>
        public static string Index_NetworkType_lb {
            get {
                return ResourceManager.GetString("Index_NetworkType_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECTIVE POINT QUALITIES.
        /// </summary>
        public static string Index_OPQual_lb {
            get {
                return ResourceManager.GetString("Index_OPQual_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECTIVE POINT TYPES.
        /// </summary>
        public static string Index_OPTypes_lb {
            get {
                return ResourceManager.GetString("Index_OPTypes_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENSOR BRANDS.
        /// </summary>
        public static string Index_SensorBrand_lb {
            get {
                return ResourceManager.GetString("Index_SensorBrand_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENSOR DEPLOYMENT TYPES.
        /// </summary>
        public static string Index_SensorDepType_lb {
            get {
                return ResourceManager.GetString("Index_SensorDepType_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENSOR STATUS TYPES.
        /// </summary>
        public static string Index_SensorStat_lb {
            get {
                return ResourceManager.GetString("Index_SensorStat_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENSOR TYPES.
        /// </summary>
        public static string Index_SensorType_lb {
            get {
                return ResourceManager.GetString("Index_SensorType_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERTICAL COLLECTION METHODS.
        /// </summary>
        public static string Index_VCollMethod_lb {
            get {
                return ResourceManager.GetString("Index_VCollMethod_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERTICAL DATUMS.
        /// </summary>
        public static string Index_VDatum_lb {
            get {
                return ResourceManager.GetString("Index_VDatum_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Instrument Collection Condition:.
        /// </summary>
        public static string InstrCollCond_createNew {
            get {
                return ResourceManager.GetString("InstrCollCond_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Marker: .
        /// </summary>
        public static string Markers_createNew {
            get {
                return ResourceManager.GetString("Markers_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Network Name:.
        /// </summary>
        public static string NetworkName_createNew {
            get {
                return ResourceManager.GetString("NetworkName_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Site Location Type in the Network:.
        /// </summary>
        public static string NetworkType_createNew {
            get {
                return ResourceManager.GetString("NetworkType_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New OP Quality:.
        /// </summary>
        public static string OPQuality_createNew {
            get {
                return ResourceManager.GetString("OPQuality_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Objective Point Type:.
        /// </summary>
        public static string OPTypes_createNew {
            get {
                return ResourceManager.GetString("OPTypes_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sensor Brand:.
        /// </summary>
        public static string SensorBrand_createNew {
            get {
                return ResourceManager.GetString("SensorBrand_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sensor Type: .
        /// </summary>
        public static string SensorType_createNew {
            get {
                return ResourceManager.GetString("SensorType_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Status Type: .
        /// </summary>
        public static string StatusType_createNew {
            get {
                return ResourceManager.GetString("StatusType_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Vertical Collect Method: .
        /// </summary>
        public static string VCollectMethod_createNew {
            get {
                return ResourceManager.GetString("VCollectMethod_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Vertical Datum:.
        /// </summary>
        public static string VDatum_createNew {
            get {
                return ResourceManager.GetString("VDatum_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Datum Abbreviation:.
        /// </summary>
        public static string VDatumAbbr_createNew {
            get {
                return ResourceManager.GetString("VDatumAbbr_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Datum Name:.
        /// </summary>
        public static string VDatumName_createNew {
            get {
                return ResourceManager.GetString("VDatumName_createNew", resourceCulture);
            }
        }
    }
}
