//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNWeb.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MemberStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MemberStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STNWeb.Assets.Resources.MemberStrings", typeof(MemberStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency: .
        /// </summary>
        public static string Agency_Label {
            get {
                return ResourceManager.GetString("Agency_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are you with (username):.
        /// </summary>
        public static string CollectTeamWho_Label {
            get {
                return ResourceManager.GetString("CollectTeamWho_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        public static string ConfirmPassword_Label {
            get {
                return ResourceManager.GetString("ConfirmPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: .
        /// </summary>
        public static string Email_Label {
            get {
                return ResourceManager.GetString("Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact Name: .
        /// </summary>
        public static string EmergencyContactName_Label {
            get {
                return ResourceManager.GetString("EmergencyContactName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact Phone: .
        /// </summary>
        public static string EmergencyContactPhone_Label {
            get {
                return ResourceManager.GetString("EmergencyContactPhone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name: .
        /// </summary>
        public static string FirstName_Label {
            get {
                return ResourceManager.GetString("FirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name: .
        /// </summary>
        public static string LastName_Label {
            get {
                return ResourceManager.GetString("LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        public static string NewPassword_Label {
            get {
                return ResourceManager.GetString("NewPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password:.
        /// </summary>
        public static string OldPassword_Label {
            get {
                return ResourceManager.GetString("OldPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password_Label {
            get {
                return ResourceManager.GetString("Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone: .
        /// </summary>
        public static string Phone_Label {
            get {
                return ResourceManager.GetString("Phone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role: .
        /// </summary>
        public static string Role_Label {
            get {
                return ResourceManager.GetString("Role_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS Feed: .
        /// </summary>
        public static string RSSFeed_Label {
            get {
                return ResourceManager.GetString("RSSFeed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name:.
        /// </summary>
        public static string TeamName_Label {
            get {
                return ResourceManager.GetString("TeamName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name: .
        /// </summary>
        public static string UserName_Label {
            get {
                return ResourceManager.GetString("UserName_Label", resourceCulture);
            }
        }
    }
}
