//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNWeb.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ObjPointsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjPointsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STNWeb.Assets.Resources.ObjPointsStrings", typeof(ObjPointsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Established: .
        /// </summary>
        public static string DateEstablished_Label {
            get {
                return ResourceManager.GetString("DateEstablished_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (MM/DD/YYYY).
        /// </summary>
        public static string DateFormat_Label {
            get {
                return ResourceManager.GetString("DateFormat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Recovered:.
        /// </summary>
        public static string DateRecovered_Label {
            get {
                return ResourceManager.GetString("DateRecovered_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string Description_Label {
            get {
                return ResourceManager.GetString("Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Objective Point Destroyed? .
        /// </summary>
        public static string DestroyedPoint_Label {
            get {
                return ResourceManager.GetString("DestroyedPoint_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation: .
        /// </summary>
        public static string Elevation_Label {
            get {
                return ResourceManager.GetString("Elevation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective Point Notes:.
        /// </summary>
        public static string ElevationNotes_Label {
            get {
                return ResourceManager.GetString("ElevationNotes_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string Name_Label {
            get {
                return ResourceManager.GetString("Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Identifier:.
        /// </summary>
        public static string OPControlIdentifier_Label {
            get {
                return ResourceManager.GetString("OPControlIdentifier_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string OPType_Label {
            get {
                return ResourceManager.GetString("OPType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        public static string Quality_label {
            get {
                return ResourceManager.GetString("Quality_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncertainty:.
        /// </summary>
        public static string Uncertainty_Label {
            get {
                return ResourceManager.GetString("Uncertainty_Label", resourceCulture);
            }
        }
    }
}
