//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNWeb.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STNWeb.Assets.Resources.SiteStrings", typeof(SiteStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: .
        /// </summary>
        public static string Address_Label {
            get {
                return ResourceManager.GetString("Address_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City: .
        /// </summary>
        public static string City_Label {
            get {
                return ResourceManager.GetString("City_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County: .
        /// </summary>
        public static string County_Label {
            get {
                return ResourceManager.GetString("County_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Description: .
        /// </summary>
        public static string Desc_Label {
            get {
                return ResourceManager.GetString("Desc_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Datum: .
        /// </summary>
        public static string HDatum_Label {
            get {
                return ResourceManager.GetString("HDatum_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Notes:.
        /// </summary>
        public static string InternalNotes_Label {
            get {
                return ResourceManager.GetString("InternalNotes_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landowner Contact:.
        /// </summary>
        public static string LandownerContact_Label {
            get {
                return ResourceManager.GetString("LandownerContact_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude: .
        /// </summary>
        public static string Latitude_Label {
            get {
                return ResourceManager.GetString("Latitude_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string LO_Email_Label {
            get {
                return ResourceManager.GetString("LO_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string LO_FirstName_Label {
            get {
                return ResourceManager.GetString("LO_FirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        public static string LO_LastName_Label {
            get {
                return ResourceManager.GetString("LO_LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Phone:.
        /// </summary>
        public static string LO_PrimaryNo_Label {
            get {
                return ResourceManager.GetString("LO_PrimaryNo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Phone:.
        /// </summary>
        public static string LO_SecondaryNo_Label {
            get {
                return ResourceManager.GetString("LO_SecondaryNo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliation/Title:.
        /// </summary>
        public static string LO_Title_Label {
            get {
                return ResourceManager.GetString("LO_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude: .
        /// </summary>
        public static string Longitude_Label {
            get {
                return ResourceManager.GetString("Longitude_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Name:.
        /// </summary>
        public static string NetworkName_Label {
            get {
                return ResourceManager.GetString("NetworkName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Location Type in the Network:.
        /// </summary>
        public static string NetworkType_Label {
            get {
                return ResourceManager.GetString("NetworkType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station ID for NOAA gage:.
        /// </summary>
        public static string NOAAStationID_Label {
            get {
                return ResourceManager.GetString("NOAAStationID_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Station ID:.
        /// </summary>
        public static string OtherStationID_Label {
            get {
                return ResourceManager.GetString("OtherStationID_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Sensor Housing Installed?.
        /// </summary>
        public static string PermSensor_Label {
            get {
                return ResourceManager.GetString("PermSensor_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority:.
        /// </summary>
        public static string Priority_Label {
            get {
                return ResourceManager.GetString("Priority_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Notes:.
        /// </summary>
        public static string SafetyNotes_Label {
            get {
                return ResourceManager.GetString("SafetyNotes_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name: .
        /// </summary>
        public static string SiteName_Label {
            get {
                return ResourceManager.GetString("SiteName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Number: .
        /// </summary>
        public static string SiteNo_Label {
            get {
                return ResourceManager.GetString("SiteNo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State: .
        /// </summary>
        public static string State_Label {
            get {
                return ResourceManager.GetString("State_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station ID for USGS gage: .
        /// </summary>
        public static string USGSStationID_Label {
            get {
                return ResourceManager.GetString("USGSStationID_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterbody: .
        /// </summary>
        public static string Waterbody_Label {
            get {
                return ResourceManager.GetString("Waterbody_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip: .
        /// </summary>
        public static string Zip_Label {
            get {
                return ResourceManager.GetString("Zip_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone:.
        /// </summary>
        public static string Zone_Label {
            get {
                return ResourceManager.GetString("Zone_Label", resourceCulture);
            }
        }
    }
}
